version: "3.9"
services:
  hotel-heritage:
    build:
      context: ../
      dockerfile: ./docker/hotel-heritage/Dockerfile
    ports:
      - "1234:1234"  # Maps to 8001 on the host
  hotel-mountain:
    build:
      context: ../
      dockerfile: ./docker/hotel-mountain/Dockerfile
    ports:
      - "2345:2345"  # Maps to 8001 on the host
  hotel-palm:
    build:
      context: ../
      dockerfile: ./docker/hotel-palm/Dockerfile
    ports:
      - "3456:3456"  # Maps to 8001 on the host
  hotel-serene:
    build:
      context: ../
      dockerfile: ./docker/hotel-serene/Dockerfile
    ports:
      - "4567:4567"  # Maps to 8001 on the host
  hotel-urban:
    build:
      context: ../
      dockerfile: ./docker/hotel-urban/Dockerfile
    ports:
      - "5678:5678"  # Maps to 8001 on the host
    