# http://json-schema.org/draft-04/schema#

openapi: "3.0.0"
info:
  title: "RestAgency api"
  description: "A description of your API"
  version: "1.0.0"
paths:
  /api/v1/rooms:
    get:
      operationId: agency.get_rooms
      description: get all rooms.
      parameters:
        - name: start-date
          in: query
          required: false
        - name: end-date
          in: query
          required: false
        - name: minsize
          in: query
          required: false
        - name: minprize
          in: query
          required: false
        - name: maxprice
          in: query
          required: false
        - name: beds
          in: query
          required: false
          schema:
            type: int
        - name: location
          in: query
          required: false
          schema:
            type: string
        - name: location_radius
          in: query
          schema:
            type: number
          required: false

      responses:
        "200":
          description: a list of rooms
          content:
            application/json:
              schema:
                type: array

  /api/v1/room/{uuid}:
    get:
      operationId:
      description: Get room detailed information.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
  /api/v1/room/{uuid}/book:
    post:
      operationId: run.post_greeting
      responses:
        200:
          description: "Greeting response"
          content:
            text/plain:
              schema:
                type: string
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: token
          in: query
          required: true
          schema:
            type: string
    delete:
      description: Cancel a room reservation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: token
          in: query
          required: true
          schema:
            type: string
        - name: reservation_id
          id: query
    patch:
      description: Update a room reservation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: token
          in: query
          required: true
          schema:
            type: string
        - name: reservation_id
          id: query
      responses:
        "200":
          description: update Successful

  /api/v1/agency/info:
    get:
      description: Agency Info
      responses:
        200:
          content:
            text/json:
              schema:
                type: object
