# http://json-schema.org/draft-04/schema#

openapi: "3.0.0"
info:
  title: "RestAPI for the comparator app"
  description: "A description of your API"
  version: "1.0.0"
servers:
  - url: http://localhost:4321/api/v1
paths:
  /agency:
    get:
      description: "Provide the list of agency endpoint"
      operationId: comparator.get_agency
      responses:
        "200":
          description: "0K"
          content:
            application/json:
              schema:
                type: array
