# http://json-schema.org/draft-04/schema#

openapi: "3.0.0"
info:
  title: "RestHotel api"
  description: "A description of your API"
  version: "1.0.0"
servers:
  - url: http://localhost:1234/api/v1
paths:
  /rooms:
    get:
      operationId: hotel.get_rooms
      description: fetch rooms with optional filter.
      parameters:
        - name: start-date
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: end-date
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: minsize
          in: query
          required: false
          schema:
            type: integer
        - name: minprize
          in: query
          required: false
          schema:
            type: number
        - name: maxprice
          in: query
          required: false
          schema:
            type: number
        - name: beds
          in: query
          required: false
          schema:
            type: integer

      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  rooms:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        size:
                          type: integer
                        price:
                          type: number

  /room/{uuid}:
    get:
      operationId: hotel.get_room_details
      description: Get room detailed information.
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  rooms:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      size:
                        type: integer
                      price:
                        type: number
  /room/{uuid}/book:
    post:
      operationId: hotel.book_room
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
        - name: token
          description: the authentication token of the agency
          in: query
          required: true
          schema:
            type: string
      requestBody:
        description: the booking
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  rooms:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      size:
                        type: integer
                      price:
                        type: number
    delete:
      operationId: hotel.cancel_room_reservation
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
        - name: token
          description: the authentication token of the agency
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ok
    patch:
      operationId: hotel.update_room_reservation
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
        - name: token
          description: the authentication token of the agency
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ok
  /room/{uuid}/images:
    get:
      operationId: hotel.get_room_images
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  rooms:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      size:
                        type: integer
                      price:
                        type: number

  /hotel/info:
    get:
      operationId: hotel.get_hotel_info
      responses:
        "200":
          description: Hotel information.
          content:
            application/json:
              schema:
                type: object
  /hotel/images:
    get:
      operationId: hotel.get_hotel_images

      responses:
        "200":
          description: A list of hotel images
          content:
            application/json:
              schema:
                type: array
